name: Deploy Blue

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

env:
  CHART_REF: oci://ghcr.io/mpegushin/test-helm-chart/test-service
  CHART_VERSION: 1.0.0

jobs:
  deploy-blue:
    runs-on: ubuntu-latest
    env:
      NAMESPACE: blue
      RELEASE: test-service
      IMAGE_NAME: ${{ github.repository }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure kubeconfig from secret
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - uses: azure/setup-helm@v4

      - name: Helm login to GHCR
        run: |
          echo "${TOKEN}" | helm registry login ghcr.io --username "${ACTOR}" --password-stdin
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTOR: ${{ github.actor }}

      - name: Helm upgrade/install
        run: |
          helm upgrade --install "${RELEASE}" "${CHART_REF}" \
            --namespace "${NAMESPACE}" \
            --version "${CHART_VERSION}" \
            --set namespace="${NAMESPACE}" \
            --set image.name="${IMAGE_NAME}" \
            --set image.tag="${IMAGE_TAG}" \
            --wait --timeout 5m
