name: Deploy Green

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

env:
  CHART_REF: oci://ghcr.io/mpegushin/test-helm-chart/test-service
  CHART_VERSION: 1.0.0

jobs:
  deploy-green:
    runs-on: ubuntu-latest
    env:
      NAMESPACE: green
      RELEASE: test-service
      IMAGE_NAME: ${{ github.repository }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure kubeconfig from secret
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - uses: azure/setup-helm@v4

      - name: Helm upgrade/install (green)
        run: |
          helm upgrade --install "${RELEASE}" "${CHART_REF}" \
            --namespace "${NAMESPACE}" \
            --version "${CHART_VERSION}" \
            --set namespace="${NAMESPACE}" \
            --set image.name="${IMAGE_NAME}" \
            --set image.tag="${IMAGE_TAG}" \
            --wait --timeout 5m

      - name: Shift traffic to GREEN (0/100)
        run: |
          kubectl -n kube-system patch ingressroute blue-green-router --type='json' -p='[
            {"op":"replace","path":"/spec/routes/0/services/0/weight","value":0},
            {"op":"replace","path":"/spec/routes/0/services/1/weight","value":100}
          ]'